# Generated by Django 5.1.3 on 2025-03-10 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepneural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='template_name',
            field=models.CharField(default=datetime.datetime(2025, 3, 10, 21, 34, 46, 957737, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
