# Generated by Django 5.1.3 on 2025-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepneural', '0002_blogs_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('template_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
